changelog:
  categories:
    - title: Security fixes
      labels:
        - security
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: New Features
      labels:
        - enhancement
        - feature
    - title: Bug Fixes
      labels:
        - bug
        - fix
    - title: Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
